services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: util_syncthing
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
    volumes:
      - ${APP_DATA_DIR}/syncthing_config:/var/syncthing/config
      - ${USER_HOME_DIR}:/var/syncthing/home

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: util_filebrowser
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    ports:
      - "8136:8080"
    volumes:
      - ${USER_HOME_DIR}:/srv
      - ${APP_DATA_DIR}/filebrowser_data/filebrowser.db:/database.db
      - ${APP_DATA_DIR}/filebrowser_config/settings.json:/config/settings.json

  silverbullet:
    image: zefhemel/silverbullet:latest
    container_name: util_silverbullet
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - ${USER_HOME_DIR}/obsidian:/space
      - ${APP_DATA_DIR}/silverbullet_data:/config
